export const staticMenus = [
  { key: 'main_menu', title: 'Главная' },
  { key: 'client_menu', title: 'Студенты' },
  { key: 'autopayment_menu', title: 'Автоплатежи' },
  { key: 'import_menu', title: 'Импорт' },
  { key: 'report_menu', title: 'Отчеты' },
  { key: 'operation_menu', title: 'Операции' },
  { key: 'events_menu', title: 'События' },
  { key: 'org_user_system_menu', title: 'Пользователи системы' },
  { key: 'overdraft_menu', title: 'Овердрафт' }
]

export const staticFunctionals = [
  { key: 'client_contract_view', value: 'Студенты и договоры' },
  { key: 'client_contract_add', value: 'Добавить заем. и договоры' },
  { key: 'client_contract_edit', value: 'Изменить заем. и договоры' },
  { key: 'client_contract_remove', value: 'Удалить заем. и договоры' },
  { key: 'wclient_contract_view', value: 'Созаемщики и Поручители' },
  { key: 'wclient_contract_state_edit', value: 'Разрешить списание по созаем./поручителям' },
  { key: 'action_on_cards', value: 'Действие по картам' },
  { key: 'personal_data_view', value: 'О персональных данных' },
  { key: 'client_white_list_view', value: 'Белый лист' },
  { key: 'client_white_list_add', value: 'Добавить (Белый лист)' },
  { key: 'client_white_list_remove', value: 'Удалить (Белый лист)' },
  { key: 'client_export', value: 'Экспортировать список' },
  { key: 'autopayment_view', value: 'Список автоплатежей' },
  { key: 'autopayment_add', value: 'Добавить автоплатеж' },
  { key: 'autopayment_pause', value: 'Остановить автоплатеж' },
  { key: 'autopayment_resume', value: 'Возобновить автоплатеж' },
  { key: 'autopayment_finish', value: 'Завершить автоплатеж' },
  { key: 'import_files_view', value: 'Импортированные файлы' },
  { key: 'import_files_add', value: 'Импортировать файл' },
  { key: 'import_error_files_view', value: 'Ошибки импортированных данных' },
  { key: 'import_error_files_export', value: 'Импортированные файлы' },
  { key: 'report_view', value: 'Просмотр транзакции' },
  { key: 'report_reverse_transaction_action', value: 'Отменить транзакцию в отчете' },
  { key: 'report_export', value: 'Экспортировать отчеты' },
  { key: 'reverse_transaction_action', value: 'Возврат средств' },
  { key: 'organization_user_view', value: 'Пользователи' },
  { key: 'organization_user_add', value: 'Добавить пользователя' },
  { key: 'organization_user_edit', value: 'Изменить пользователя' },
  { key: 'organization_user_role_view', value: 'Роли' },
  { key: 'organization_user_role_add', value: 'Добавить роли' },
  { key: 'organization_user_role_edit', value: 'Изменить роли' },
  { key: 'organization_branch_view', value: 'Филиалы' },
  { key: 'organization_branch_add', value: 'Добавить филиал' },
  { key: 'organization_branch_edit', value: 'Изменить филиал' },
  { key: 'organization_events_view', value: 'Список событий' },
  { key: 'organization_incident_application_view', value: 'Заявки на инцендент' },
  { key: 'organization_incident_application_add', value: 'Добавить заявку на инцендент' },
  { key: 'overdraft_autopayment_view', value: 'Овердрафт автоплатежи' },
  { key: 'overdraft_autopayment_add', value: 'Добавить автоплатеж (Овердрафт)' },
  { key: 'overdraft_autopayment_edit', value: 'Изменить автоплатеж (Овердрафт)' },
  { key: 'overdraft_transaction_view', value: 'Овердрафт транзакции' },
  { key: 'overdraft_transaction_reverse', value: 'Отменить транзакцию (Овердрафт)' }
]
